version: '2'
services:

    task_db:
        image: postgres
        restart: always
        expose: 
            - "5432"
        networks:
            - default

    rabbitmq:
        image: rabbitmq
        restart: always
        expose:
            - "5672"
        networks:
            - default

    consumer:
        build: ./consumer
        restart: always
        links:
            - rabbitmq
            - task_db 
        networks:
            - default
